name: Write Version to File

on:
  release:
    types: [ created ]

permissions: write-all

jobs:
  write-version:
    runs-on: ubuntu-latest
    name: Write Version to File
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Write Version to File
        uses: brettdorrans/write-version-to-file@v1.1.0
        with:
          filename: 'version.txt'
          placeholder: '${VERSION}'

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Generate build
