name: Write Version to File
on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  write-version:
    runs-on: ubuntu-latest
    name: Write Version to File
    steps:
      - uses: actions/checkout@v4
      - name: Write Version to File
        uses: brettdorrans/write-version-to-file@v1.1.0
        with:
          filename: 'version.txt'
          placeholder: '${VERSION}'
